=== robert-koch-institut/mex-editor/src/assets/schema/entities/contact-point.json
{
  "$id": "https://mex.rki.de/schema/entities/contact-point",
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "properties": {
    "email": {
      "items": {
        "examples": ["info@rki.de"],
        "format": "email",
        "type": "string"
      },
      "minItems": 1,
      "sameAs": ["http://www.w3.org/2006/vcard/ns#hasEmail", "https://schema.org/email"],
      "type": "array"
    },
    "hadPrimarySource": {
      "$ref": "/schema/entities/primary-source#/identifier",
      "sameAs": ["http://www.w3.org/ns/prov#hadPrimarySource"]
    },
    "identifier": {
      "$ref": "/schema/fields/identifier",
      "sameAs": ["http://purl.org/dc/elements/1.1/identifier"]
    },
    "identifierInPrimarySource": {
      "examples": ["123456", "item-501", "D7/x4/zz.final3"],
      "minLength": 1,
      "type": "string"
    },
    "stableTargetId": {
      "examples": ["00000000-0000-4000-8000-00000000002a"],
      "format": "uuid",
      "type": "string"
    }
  },
  "required": ["email", "hadPrimarySource", "identifier", "identifierInPrimarySource", "stableTargetId"],
  "sameAs": ["https://schema.org/ContactPoint"],
  "title": "Contact Point",
  "type": "object"
}

=== robert-koch-institut/mex-editor/src/assets/data/contact-point.json
[
  {
    "email": ["joseph38@example.com"],
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff358a#merged",
    "identifier": "d9067ab2-4860-4782-9284-4f5764768d9a",
    "identifierInPrimarySource": "ContactPoint-4181830114",
    "stableTargetId": "00000000-0000-4000-8000-0000f941a9eb"
  },
  {
    "email": ["faulknercody@example.com"],
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3588#merged",
    "identifier": "aca7ed7d-40c7-48d0-843e-34dcdc3e5e9f",
    "identifierInPrimarySource": "ContactPoint-4181830115",
    "stableTargetId": "00000000-0000-4000-8000-0000f941a9e4"
  },
  {
    "email": ["hans-hinrichwahner@example.org"],
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3598#merged",
    "identifier": "547c535d-aa95-4535-bf23-e7e2308b6f72",
    "identifierInPrimarySource": "ContactPoint-4181830116",
    "stableTargetId": "00000000-0000-4000-8000-0000f941a9e4"
  },
  {
    "email": ["robertsonrobert@example.net"],
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff359a#merged",
    "identifier": "ab5b86eb-1cbe-4dbe-b7cd-1a89fc177aea",
    "identifierInPrimarySource": "ContactPoint-4181830117",
    "stableTargetId": "00000000-0000-4000-8000-0000f941a9e3"
  },
  {
    "email": ["textorreimar@example.org"],
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3594#merged",
    "identifier": "6743577d-fcc4-45f5-96e1-58ff1fded78d",
    "identifierInPrimarySource": "ContactPoint-4181830118",
    "stableTargetId": "00000000-0000-4000-8000-0000f941a9e6"
  },
  {
    "email": ["fitzpatrickmichael@example.net"],
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3581#merged",
    "identifier": "5b1bbaeb-27cc-4d47-90c5-827f42f4223b",
    "identifierInPrimarySource": "ContactPoint-4181830119",
    "stableTargetId": "00000000-0000-4000-8000-0000f941a9e7"
  },
  {
    "email": ["ericpeterson@example.com"],
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3594#merged",
    "identifier": "37c90d0a-4488-4b26-a4a6-b3f97dd3a6c4",
    "identifierInPrimarySource": "ContactPoint-4181830120",
    "stableTargetId": "00000000-0000-4000-8000-0000f941a9e2"
  },
  {
    "email": ["pcarter@example.org"],
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3594#merged",
    "identifier": "d863526d-aba7-469a-9189-448391b561e7",
    "identifierInPrimarySource": "ContactPoint-4181830121",
    "stableTargetId": "00000000-0000-4000-8000-0000f941a9e9"
  },
  {
    "email": ["ehrhard18@example.com"],
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff359b#merged",
    "identifier": "a1cc3588-987f-4b05-a881-35aa93922857",
    "identifierInPrimarySource": "ContactPoint-4181830122",
    "stableTargetId": "00000000-0000-4000-8000-0000f941a9ea"
  },
  {
    "email": ["duane31@example.net"],
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff358b#merged",
    "identifier": "ec5fc99a-f4b5-4d2a-8152-3d721a69d40c",
    "identifierInPrimarySource": "ContactPoint-4181830123",
    "stableTargetId": "00000000-0000-4000-8000-0000f941a9eb"
  }
]
