=== robert-koch-institut/mex-editor/src/assets/schema/entities/organization.json
{
  "$id": "https://mex.rki.de/schema/entities/organization",
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "properties": {
    "alternativeName": {
      "items": {
        "$ref": "/schema/fields/text"
      },
      "sameAs": ["http://purl.org/dc/terms/alternative"],
      "type": "array"
    },
    "geprisId": {
      "examples": ["https://gepris.dfg.de/gepris/institution/10179"],
      "format": "uri",
      "pattern": "^https://gepris\\.dfg\\.de/gepris/institution/[0-9]{1,64}$",
      "sameAs": ["http://www.wikidata.org/entity/P4871"],
      "type": "string"
    },
    "gndId": {
      "examples": ["https://d-nb.info/gnd/17690-4"],
      "format": "uri",
      "pattern": "^https://d\\-nb\\.info/gnd/[-X0-9]{3,10}$",
      "sameAs": ["http://www.wikidata.org/entity/P227"],
      "type": "string"
    },
    "hadPrimarySource": {
      "$ref": "/schema/entities/primary-source#/identifier",
      "sameAs": ["http://www.w3.org/ns/prov#hadPrimarySource"]
    },
    "identifier": {
      "$ref": "/schema/fields/identifier",
      "sameAs": ["http://purl.org/dc/elements/1.1/identifier"]
    },
    "identifierInPrimarySource": {
      "examples": ["123456", "item-501", "D7/x4/zz.final3"],
      "minLength": 1,
      "type": "string"
    },
    "isniId": {
      "examples": ["https://isni.org/isni/0000000109403744"],
      "format": "uri",
      "pattern": "^https://isni\\.org/isni/[X0-9]{16}$",
      "sameAs": ["http://www.wikidata.org/entity/P213"],
      "type": "string"
    },
    "officialName": {
      "items": {
        "$ref": "/schema/fields/text"
      },
      "minItems": 1,
      "sameAs": ["http://www.wikidata.org/entity/P1448"],
      "type": "array"
    },
    "rorId": {
      "examples": ["https://ror.org/01k5qnb77"],
      "format": "uri",
      "pattern": "^https://ror\\.org/[a-z0-9]{9}$",
      "sameAs": ["http://www.wikidata.org/entity/P6782"],
      "type": "string"
    },
    "shortName": {
      "items": {
        "$ref": "/schema/fields/text"
      },
      "sameAs": ["http://www.wikidata.org/entity/P1813"],
      "type": "array"
    },
    "stableTargetId": {
      "examples": ["00000000-0000-4000-8000-00000000002a"],
      "format": "uuid",
      "type": "string"
    },
    "viafId": {
      "examples": ["https://viaf.org/viaf/123556639"],
      "format": "uri",
      "pattern": "^https://viaf\\.org/viaf/[1-9]{2,22}$",
      "sameAs": ["http://www.wikidata.org/entity/P214"],
      "type": "string"
    },
    "wikidataId": {
      "examples": ["http://www.wikidata.org/entity/Q679041"],
      "format": "uri",
      "pattern": "^https://www\\.wikidata\\.org/entity/[PQ0-9]{2,64}$",
      "type": "string"
    }
  },
  "required": ["hadPrimarySource", "identifier", "identifierInPrimarySource", "officialName", "stableTargetId"],
  "sameAs": ["http://www.w3.org/ns/org#Organization"],
  "title": "Organization",
  "type": "object"
}

=== robert-koch-institut/mex-editor/src/assets/data/organization.json
[
  {
    "geprisId": "https://gepris.dfg.de/gepris/institution/1027357",
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3590#merged",
    "identifier": "4a6cef44-abf4-4550-beb9-e6fef8f09517",
    "identifierInPrimarySource": "Organization-991028314",
    "officialName": [
      "Fressen Woche Monat einfach gestern Mama Auto. Nein verstecken gestern bauen. Ferien sp\u00e4ter vergessen hat Abend endlich. Sommer sind kam Kind Land Oma."
    ],
    "rorId": "https://ror.org/872778300",
    "stableTargetId": "00000000-0000-4000-8000-00003b11e45a",
    "viafId": "https://viaf.org/viaf/106535603",
    "wikidataId": "http://www.wikidata.org/entity/P525775"
  },
  {
    "alternativeName": [
      "Here provide despite only growth this interest. Until already mouth source crime. Wear option take case almost central article. Notice game someone doctor above. Security car simple tree will.",
      "Husband turn religious then.",
      "Wo gab bleiben braun Fisch gr\u00fcn bis. Zeitung Wissen etwas fehlen gleich bleiben. Zur wohl ab Dorf. Rot Bein erschrecken bauen f\u00fchren nicht."
    ],
    "geprisId": "https://gepris.dfg.de/gepris/institution/1879012",
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3588#merged",
    "identifier": "fbb0e728-5ba8-4b60-8fba-3e8a34e3d3c4",
    "identifierInPrimarySource": "Organization-991028315",
    "officialName": [
      "Gut ziehen Winter kurz Monate alle. Tisch war Zimmer lange Hunger stellen bis. Wiese Geld viel trinken Welt. Scheinen hei\u00dfen Stein oben den nat\u00fcrlich. Fliegen deshalb Stein Stra\u00dfe Feuer. Familie Winter ab krank. Da wichtig noch los vom Sonne schwarz. Eltern liegen Spa\u00df Ende darin schicken erst. Kennen Platz Stra\u00dfe beide mich Herr sagen. Seit lustig lassen f\u00e4hrt gl\u00fccklich."
    ],
    "shortName": [
      "West realize question modern. Wish apply interest administration call. Realize development kitchen able girl reason glass. Visit life no action need perhaps. Local idea someone beat pressure write environmental. Finally team stay trip guess. Head social performance cell onto this. Throw discuss family prepare answer. Dinner voice ability level. Book until particularly mission thank share remember.",
      "Eltern Zug um wo nehmen. Dein Apfel denken Baum. M\u00f6gen Gl\u00fcck stellen Fenster aber. Sind dauern sprechen wei\u00df Zeit. Sicher Dorf wer nah. Vorbei Himmel dem brauchen nehmen rund gl\u00fccklich. Denn w\u00fcnschen Schnee darin. Werden gehen nennen M\u00e4dchen mich."
    ],
    "stableTargetId": "00000000-0000-4000-8000-00003b11e45b",
    "viafId": "https://viaf.org/viaf/183868362",
    "wikidataId": "http://www.wikidata.org/entity/P205732"
  },
  {
    "gndId": "https://d-nb.info/gnd/332984617",
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3589#merged",
    "identifier": "454f01e4-03ab-4a85-9294-80b8ccf85c4c",
    "identifierInPrimarySource": "Organization-991028316",
    "isniId": "https://isni.org/isni/0831678334620470",
    "officialName": ["Hope option record to. Certainly who reason campaign."],
    "shortName": [
      {
        "language": "de",
        "value": "Kam Angst mit Arzt. Schwimmen Bild Sonntag wollen Himmel Freund weil halbe. Tag haben Haare zur Mutter brauchen verstehen. Schuh schlimm Bett hart sagen. Gewinnen wenig zur\u00fcck gleich rennen bleiben. Aus dauern spielen Uhr Gl\u00fcck sitzen. Dein Licht wohnen ziehen geh\u00f6ren Schluss. Luft hier nimmt Hilfe Kind Minute. Deshalb Feuer danach essen. Arzt sie Blume Land weinen rennen wenn. Arbeiten helfen beide wie."
      }
    ],
    "stableTargetId": "00000000-0000-4000-8000-00003b11e45a",
    "viafId": "https://viaf.org/viaf/198520573"
  },
  {
    "alternativeName": [
      "Cost impact actually range vote resource. Form economic film staff. Toward great very south government goal. Not benefit tax those door according paper. Lot to international trial strategy hot.",
      "Arbeiten kaufen kennen ab. Hund gr\u00fcn fahren Zeit auf fallen. Selbst geben Mutter Vogel. Ziehen Meer er rechnen weil will ins. Kaufen vorbei weg nichts Wetter leben. W\u00fcnschen Brot Stunde zusammen oft n\u00e4mlich sie."
    ],
    "geprisId": "https://gepris.dfg.de/gepris/institution/1418959",
    "gndId": "https://d-nb.info/gnd/361681565",
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff358b#merged",
    "identifier": "b13b6207-aed7-4f0e-814f-0eba6d4fef28",
    "identifierInPrimarySource": "Organization-991028317",
    "officialName": [
      "Onkel las Geschenk in bringen hoch singen. Gesicht stellen Geschenk. Dunkel wahr gegen Affe nur schlecht. Drau\u00dfen alt und Baum Apfel Wagen. Treffen alt bald. Sechs dazu singen Junge kurz Leben. Fr\u00f6hlich weg Loch wohl. Einigen dumm verlieren rufen. \u00dcberall viel ziehen dazu glauben. Schwarz \u00f6ffnen ihn wohnen davon Schwester. Danach Wort Minutenmir trinken."
    ],
    "shortName": [
      "Be human work level light anything. Bed production worry west. Discover media still. Card successful even trade.",
      "Ahead decide into newspaper develop economy."
    ],
    "stableTargetId": "00000000-0000-4000-8000-00003b11e45d"
  },
  {
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3594#merged",
    "identifier": "07d4ef8d-a17b-40d2-aa6f-0c481c617dd2",
    "identifierInPrimarySource": "Organization-991028318",
    "officialName": ["Einigen werden haben Minute auch weit sehen blau. Geh\u00f6ren einige kam."],
    "rorId": "https://ror.org/916278223",
    "shortName": ["Current small evening we."],
    "stableTargetId": "00000000-0000-4000-8000-00003b11e45e",
    "viafId": "https://viaf.org/viaf/121804835"
  },
  {
    "alternativeName": [
      "Wait compare they few across pass ready. Cold adult student arrive allow there. Statement adult apply. Result care seem join life manage. Even tonight minute well. Country common system production."
    ],
    "geprisId": "https://gepris.dfg.de/gepris/institution/1561669",
    "gndId": "https://d-nb.info/gnd/301623887",
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3599#merged",
    "identifier": "a82d4062-5546-4882-83db-4e7382e5f39c",
    "identifierInPrimarySource": "Organization-991028319",
    "officialName": [
      "Verstecken Apfel wohl Auge neun. Am Onkel verlieren ziehen Sommer mit. Hat machen m\u00f6gen Tisch spielen Klasse steigen."
    ],
    "rorId": "https://ror.org/280311413",
    "stableTargetId": "00000000-0000-4000-8000-00003b11e45f",
    "wikidataId": "http://www.wikidata.org/entity/P419207"
  },
  {
    "alternativeName": [
      "Dort Ball Blume Gesicht dich dunkel Auto Brief. Sonst vorbei bei springen essen Leben Bein M\u00e4dchen. Schiff es \u00fcber fertig Wald tief sein damit. Versuchen Geburtstag unten Vogel werfen allein f\u00fcr.",
      "Call result budget whether."
    ],
    "geprisId": "https://gepris.dfg.de/gepris/institution/1556662",
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3595#merged",
    "identifier": "990c6205-6b73-4e71-966d-f74920e71814",
    "identifierInPrimarySource": "Organization-991028320",
    "officialName": [
      "Zu kochen drehen schauen packen. Drehen Sache gehen wir. Sofort Fisch lange Name. Merken fr\u00f6hlich Katze Zeitung nach gerade. Mann Brief wollen fressen."
    ],
    "stableTargetId": "00000000-0000-4000-8000-00003b11e460"
  },
  {
    "alternativeName": ["Dunkel heute fr\u00fch schenken erst Papa Hand."],
    "geprisId": "https://gepris.dfg.de/gepris/institution/1037264",
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3595#merged",
    "identifier": "625a7e6b-0d72-4762-9ee5-44fb3965a438",
    "identifierInPrimarySource": "Organization-991028321",
    "isniId": "https://isni.org/isni/3026168156541895",
    "officialName": [
      "Darauf sieht damit Dorf. Loch zur pl\u00f6tzlich lustig. Hand f\u00e4hrt Name deshalb die verstehen. Viel gestern warm Blume wohl. Schlimm Blume ihn fahren. Schluss turnen turnen klein packen. Um heraus ich wahr deshalb Name. Treffen wissen einigen Sonntag kann. Reiten erst sind und acht. Erst Monate n\u00e4mlich in einige. Wald Angst wei\u00df Frau."
    ],
    "shortName": [
      "Apfel Bett schlimm Meer auch Bruder Weg Monate. Finden Frau lieb Hilfe. Wenig Lehrerin Nase weit. Wohnung weil leben erkl\u00e4ren Frage Seite ziehen. Leicht f\u00e4hrt Wohnung unten Familie K\u00fcche fahren sieben. Schreien n\u00e4mlich was leise bis tot Bruder ein. Schaffen gut Stelle w\u00fcnschen zum Weg. Mann weit darin fressen hinter.",
      "Himmel Winter w\u00fcnschen."
    ],
    "stableTargetId": "00000000-0000-4000-8000-00003b11e461",
    "viafId": "https://viaf.org/viaf/182097779",
    "wikidataId": "http://www.wikidata.org/entity/P056653"
  },
  {
    "alternativeName": ["General watch find five behavior beat."],
    "gndId": "https://d-nb.info/gnd/365651198",
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3597#merged",
    "identifier": "8be0e588-7cbc-4fff-9072-62f6250f9fec",
    "identifierInPrimarySource": "Organization-991028322",
    "officialName": ["Rund reich Rad w\u00fcnschen glauben glauben sofort."],
    "rorId": "https://ror.org/233444457",
    "shortName": ["Schwer hier war blau Haare schlimm wieder noch."],
    "stableTargetId": "00000000-0000-4000-8000-00003b11e462"
  },
  {
    "alternativeName": ["Economic long on speech."],
    "gndId": "https://d-nb.info/gnd/356199330",
    "hadPrimarySource": "00000000-0000-4000-8000-000095ff3595#merged",
    "identifier": "fb792ab7-7049-4c17-ae8b-9bffa55fba5a",
    "identifierInPrimarySource": "Organization-991028323",
    "isniId": "https://isni.org/isni/2356841709976417",
    "officialName": [
      "Writer pick pay score. Idea country two government network American traditional. Because too film cost key at them. Decide sure science. And over glass believe land and. Newspaper rich half more. Ability test fish reach follow today sit. Television because away political. Want respond issue region those."
    ],
    "shortName": [
